spring:
  profiles:
    active: local
    group:
      local: common, secret
---
server:
  port: 8081
  servlet:
    encoding:
      force: true
      enabled: true
      charset: utf-8
    context-path: /
spring:
  cloud:
    gcp:
      storage:
        credentials:
          location: classpath:tidal-pathway-419203-b177acd7ad62.json
        project-id: tidal-pathway-419203
        bucket: kr-game-sale
  config:
    activate:
      on-profile: common
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    hibernate:
      ddl-auto: update
      # JDBC TimeZone Setting
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul
        use_sql_comments: true
  mvc:
    view:
      prefix: templates/
      suffix: .html
  mail:
    host: smtp.gmail.com
    port: 587
    username: wonwooseo23
    password: lzmf zwoe ibda lwdy
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  thymeleaf:
    cache: false
imp:
  code: imp15605565
  api:
    key: 5432765074133245
    secretkey: gqcBfcBCn2aJRMm1Udc9t3Rl2xGJLW2MsjgDysh2NjVRHqX1FeTKEKD9W1U5xJrBBdpe49iiLQweIokv
steamspyAPI:
  baseUrl: https://steamspy.com/api.php

steamAPI:
  baseUrl: https://store.steampowered.com

logging:
  level:
    org.hibernate.SQL: debug